name: "Create weekly build"
on:
  # schedule:
  #   - cron: "0 0 * * *"
  push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: "godotengine/godot"
          token:
            ${{ secrets.GITHUB_TOKEN }}
            # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0

      - name: Set up MinGW
        if: runner.os == 'Linux'
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: Install MSVC
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Other Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3 scons
          ls
      - name: Build GODOT
        run: scons -j6 platform=windows target=release_debug bits=64
